# Generated by Django 4.0.2 on 2022-02-08 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('invoice_no', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_manages', to='pharmacy.invoice')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
