# Generated by Django 4.0.2 on 2022-02-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemanage',
            name='invoice_no',
            field=models.CharField(max_length=500),
        ),
    ]
