# Generated by Django 4.0.2 on 2022-02-08 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_invoicemanage_invoice_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descrition', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacists', to='pharmacy.invoice')),
            ],
        ),
    ]
