# Generated by Django 4.0.2 on 2022-02-08 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_medicine_medicinedescription_delete_medicinecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer_descriptions', to='pharmacy.customer')),
                ('medicine', models.ManyToManyField(to='pharmacy.MedicineDescription')),
            ],
        ),
    ]
