# Generated by Django 4.0.2 on 2022-02-08 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_whoweare_whowearedescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='onlinemedicine_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onlinemedicine', to='pharmacy.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onlinemedicine', to='pharmacy.invoice')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onlinemedicine', to='pharmacy.medicine')),
            ],
        ),
        migrations.RenameModel(
            old_name='WhoWeAre',
            new_name='onlinemedicine',
        ),
        migrations.DeleteModel(
            name='WhoWeAreDescription',
        ),
    ]
